name: 'Readme Generator'
on:
  push:
    branches:
     - main
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  readme:
    name: "Readme generator"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_BOT }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "docs: update generated readme"
          branch: main
          commit_user_name: mrsimonemms
          commit_user_email: simon@simonemms.com
          commit_author: mrsimonemms <simon@simonemms.com>
