name: Repo Setup
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:
env:
  ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  list_repos:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.repos.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Get repositories
        id: repos
        working-directory: repo-settings-sync
        run: |
          repos=$(./scripts.sh get_all_repos "${{ env.ACTIONS_TOKEN }}")

          echo "matrix={\"repo\":$(echo ${repos})}" >> "$GITHUB_OUTPUT"

  apply_settings:
    runs-on: ubuntu-latest
    needs:
      - list_repos
      - shellcheck
    strategy:
      matrix: ${{ fromJSON(needs.list_repos.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3

      - name: Check for custom settings
        id: settings
        working-directory: repo-settings-sync
        run: |
          custom_settings=$(./scripts.sh get_file_from_repo "${{ env.ACTIONS_TOKEN }}" "${{ matrix.repo }}" ".github-settings.json" || echo "{}")

          echo $custom_settings > /tmp/custom_settings.raw.json

          if [ "$(cat /tmp/custom_settings.raw.json | jq '.branch_protection.required_status_checks')" != "null" ]; then
            echo "Branch protection settings in repo - do not overwrite"
            mv /tmp/custom_settings.raw.json /tmp/custom_settings.json
          else
            echo "Apply default branch protection settings"

            required_status_checks_raw=$(./scripts.sh get_required_status_checks "${{ env.ACTIONS_TOKEN }}" "${{ matrix.repo }}" || echo "{}")
            required_status_checks=$(echo "${required_status_checks_raw}" | jq -rc 'to_entries | map(select(.key | in({"checks": 1, "strict": 1}))) | from_entries')

            jq --argjson checks "${required_status_checks}" 'setpath(["branch_protection","required_status_checks"]; $checks)' /tmp/custom_settings.raw.json > /tmp/custom_settings.json
          fi

          settings=$(jq -s '.[0] * .[1]' ./settings.json /tmp/custom_settings.json)

          echo "${settings} | jq -r"

          echo "settings=$(echo "${settings}" | jq -rc)" >> "$GITHUB_OUTPUT"
          echo "apply_update=$(echo "${settings}" | jq -r '.ignore |= not | .ignore')" >> "$GITHUB_OUTPUT"

      - name: Apply settings
        if: ${{ fromJSON(steps.settings.outputs.apply_update) }}
        working-directory: repo-settings-sync
        run: |
          ./scripts.sh apply_repo_update \
            "${{ env.ACTIONS_TOKEN }}" \
            "${{ matrix.repo }}" \
            "$(echo '${{ steps.settings.outputs.settings }}' | jq -rc '.repo')"

          ./scripts.sh apply_branch_protection \
            "${{ env.ACTIONS_TOKEN }}" \
            "${{ matrix.repo }}" \
            "$(echo '${{ steps.settings.outputs.settings }}' | jq -rc '.branch_protection')"
